// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03GwDJhzENOpCIzuDyA7Rlt8ngmVssB4',
    appId: '1:366066709229:web:d5681b43c5e1a823fcd2e4',
    messagingSenderId: '366066709229',
    projectId: 'flutly-firebase',
    authDomain: 'flutly-firebase.firebaseapp.com',
    storageBucket: 'flutly-firebase.appspot.com',
    measurementId: 'G-ZE0YFR20ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSe8EKePblAOoD2slyAA6AfL0dMUpwRs0',
    appId: '1:366066709229:android:34b94e8086772fabfcd2e4',
    messagingSenderId: '366066709229',
    projectId: 'flutly-firebase',
    storageBucket: 'flutly-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACU2HOvEu7oTcjuOc_U5852CtOJpKofh0',
    appId: '1:366066709229:ios:799f0e18ca0cc57bfcd2e4',
    messagingSenderId: '366066709229',
    projectId: 'flutly-firebase',
    storageBucket: 'flutly-firebase.appspot.com',
    iosClientId: '366066709229-lq9kd5q82bn3blhf1rb8qbv0a4kl1ibb.apps.googleusercontent.com',
    iosBundleId: 'io.github.flutly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACU2HOvEu7oTcjuOc_U5852CtOJpKofh0',
    appId: '1:366066709229:ios:799f0e18ca0cc57bfcd2e4',
    messagingSenderId: '366066709229',
    projectId: 'flutly-firebase',
    storageBucket: 'flutly-firebase.appspot.com',
    iosClientId: '366066709229-lq9kd5q82bn3blhf1rb8qbv0a4kl1ibb.apps.googleusercontent.com',
    iosBundleId: 'io.github.flutly',
  );
}
